# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

env:
  DB_PASS: ${{ vars.DB_PASS }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          MSSQL_SA_PASSWORD: ${{ vars.DB_PASS }}
          ACCEPT_EULA: 'Y'
          MSSQL_PID: Express
        ports:
        - 1433:1433
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up Database
      run: |
        # Create the database if it does not exist
        sqlcmd -S localhost -U SA -P '${{ vars.DB_PASS }}' -d master -Q "IF DB_ID('TESTDB') IS NULL BEGIN CREATE DATABASE TESTDB; END;"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
